name: Unity Tests

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Run ${{ matrix.testMode }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode: [ editmode, playmode ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.testMode }}-${{ hashFiles('**/Packages/manifest.json') }}

      - name: Unity - Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          testMode: ${{ matrix.testMode }}
          unityVersion: 6000.1.13f1
          artifactsPath: TestLogs

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.testMode }}-results
          path: TestLogs